/*  
	Author Sangeeta Palankar
    date 28/12/2022
    Database Creation
*/
CREATE DATABASE KBMS_PROJECT;
USE KBMS_PROJECT;
CREATE TABLE USER
(
  NAME VARCHAR(50) NOT NULL ,
  EMAIL VARCHAR(30) unique not null,
  PHONE_NO CHAR(12) NOT NULL,
  ADDRESS TEXT NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  ID_PROOF char(12) NOT NULL,
  LOGIN_ID INT AUTO_INCREMENT ,
  PASSWORD VARCHAR(20) ,
  PRIMARY KEY(LOGIN_ID)
)AUTO_INCREMENT = 1000;

CREATE TABLE PRODUCT
(
	PRODUCT_ID INT auto_increment PRIMARY KEY ,
   PRODUCT_NAME TEXT NOT NULL,
   PRODUCT_COUNT INT,
   TOTAL_STOCK INT NOT NULL,
   BEST_BEFORE DATE,
   PRICE_PER_UNIT INT NOT NULL ,
) auto_increment=10001;

CREATE TABLE ORDER_DETAILS
(
   ORDER_ID INT PRIMARY KEY ,
   PRODUCT_NAME TEXT ,
   QUANTITY TINYINT NOT NULL,
   TOTAL_PRICE INT NOT NULL,
   STATUS BOOLEAN DEFAULT(1),
   LOGIN_ID INT NOT NULL ,
   PRODUCT_ID INT,
   fOREIGN KEY(LOGIN_ID) REFERENCES USER(LOGIN_ID),
   FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);