/*  
	Author Sangeeta Palankar
    date 28/12/2022
    Database Creation
*/
DROP DATABASE KBMS_PROJECT;

CREATE DATABASE KBMS_PROJECT;
USE KBMS_PROJECT;
CREATE TABLE USER
(
  FNAME VARCHAR(50) NOT NULL,
  LNAME VARCHAR(30) NOT NULL,
  EMAIL VARCHAR(30) unique not null,
  PHONE_NO CHAR(12) NOT NULL,
  ADDRESS TEXT NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  ID_PROOF char(12) NOT NULL,
  LOGIN_ID VARCHAR(10) NOT NULL PRIMARY KEY,
  PASSWORD VARCHAR(20)
);

CREATE TABLE PRODUCT
(
	PRODUCT_ID INT auto_increment PRIMARY KEY ,
   PRODUCT_NAME TEXT NOT NULL,
   PRODUCT_COUNT INT,
   TOTAL_STOCK INT NOT NULL,
   BEST_BEFORE DATE,
   PRICE_PER_UNIT DOUBLE NOT NULL 
) auto_increment=10001;

CREATE TABLE ORDER_DETAILS
(
   ORDER_ID INT PRIMARY KEY ,
   PRODUCT_NAME TEXT ,
   QUANTITY TINYINT NOT NULL,
   TOTAL_PRICE DOUBLE NOT NULL,
   STATUS BOOLEAN DEFAULT(1),
   LOGIN_ID VARCHAR(10) NOT NULL ,
   PRODUCT_ID INT,
   FOREIGN KEY(LOGIN_ID) REFERENCES USER(LOGIN_ID),
   FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
)auto_increment=1001;

CREATE TABLE CANCELLATION
(
	CANCELLATION_ID VARCHAR(10) UNIQUE,
    CANCELLATION_DATE DATE,
    CANCELLATION_REASON TEXT,
    ORDER_ID INT,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDER_DETAILS(ORDER_ID)
)

    
    