/*  
	Author Sangeeta Palankar
    date 28/12/2022
    DQL SCRIPTS
*/
SELECT * FROM PRODUCT;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDER_DETAILS where PREFERRED_LOGIN_ID = "alexa_";
SELECT PRODUCT_ID FROM ORDER_DETAILS WHERE ORDER_ID = 10002;
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_COUNT, BEST_BEFORE, PRICE_PER_UNIT, TYPE_OF_PRODUCT FROM PRODUCT;
