/*  
	Author Sangeeta Palankar
    date 28/12/2022
    DQL SCRIPTS
*/
SELECT * FROM PRODUCT;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDER_DETAILS;
SELECT PRODUCT_ID FROM ORDER_DETAILS WHERE ORDER_ID = 10002;
