SELECT C.CANCELLATION_ID, C.CANCELLATION_DATE, C.CANCELLATION_REASON, C.ORDER_ID, O.PRODUCT_ID, O.PRODUCT_NAME, O.QUANTITY, O.TOTAL_PRICE, O.LOGIN_ID
FROM CANCELLATION C
INNER JOIN ORDER_DETAILS O ON C.ORDER_ID = O.ORDER_ID;