/*tO GET PRODUCT ID AND PRODUCT NAME IN ORDER DETAILS*/
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.ORDER_ID
FROM PRODUCT P JOIN  ORDER_DETAILS O ON P.PRODUCT_ID = O.PRODUCT_ID;

UPDATE PRODUCT p join order_details o on p.PRODUCT_ID=o.PRODUCT_ID set PRODUCT_COUNT=(p.PRODUCT_COUNT+o.QUANTITY ) where p.PRODUCT_ID=101;
